version: '3.1'
services:
  app:
    image: "danslarue/homeless:latest"
    restart: "no"
    ports:
      - "9090:8080"
    container_name: 'app-homeless'
    depends_on:
      - db
    env_file: .env
    networks:
      - dakar-network

  db:
    image: postgres
    restart: "no"
    container_name: 'app-db'
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - dakar-network

  adm:
    image: adminer
    restart: "no"
    container_name: 'app-adm'
    ports:
      - 7070:8080
    networks:
      - dakar-network

networks:
  dakar-network:
    driver: bridge
