version: '3.1'

services:
  api:
    image: "danslarue/homeless:latest"
    restart: always
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - "node.labels.project==dakar"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeless-api.rule=Host(`homeless-api.project.lambla.eu`)"
        - "traefik.http.routers.homeless-api.entrypoints=web"
        - "traefik.http.routers.homeless-ssl-api.rule=Host(`homeless-api.project.lambla.eu`)"
        - "traefik.http.routers.homeless-ssl-api.entrypoints=websecure"
        - "traefik.http.services.homeless-api.loadbalancer.server.port=443"
        - "traefik.docker.network=traefik_traefik"
        - "traefik.http.routers.homeless-ssl-api.tls=true"
        - "traefik.http.routers.homeless-ssl-api.tls.certresolver=myresolver"
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
        - "traefik.http.routers.homeless-api.middlewares=test-redirectscheme@docker"
    networks:
      #- homeless_private
      - traefik_traefik
    environment:
      - COMPOSE_PROJECT_NAME=homeless
      - PROFILE=prod
      - db-password=example

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - post:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - "node.labels.project==dakar"
    networks:
      - traefik_traefik

  adminer:
    image: adminer
    restart: always
    deploy:
      placement:
        constraints:
          - "node.labels.project==dakar"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.entrypoints=web,websecure"
        - "traefik.http.routers.adminer.rule=Host(`adminer.project.lambla.eu`)"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik_traefik"
    networks:
      #- homeless_private
      - traefik_traefik

volumes:
  post:
    driver: local
    driver_opts:
      type: none
      device: /home/dreaser/homeless/postgres/var/lib/postgresql/data
      o: bind

networks:
  #  homeless_private:
  #   driver: overlay
  #  external: false
  traefik_traefik:
    driver: overlay
    external: true
