version: '3.1'
services:
  app:
    image: "danslarue/homeless:latest"
    env_file: .env
    restart: always
    ports:
      - "9090:8080"
    container_name: 'app-homeless'
    depends_on:
      - db
    networks:
      - dakar-network

  db:
    image: postgres
    restart: always
    env_file: .env
    container_name: 'app-db'
    volumes:
      - post:/var/lib/postgresql/data
    networks:
      - dakar-network

  adm:
    image: adminer
    restart: always
    container_name: 'app-adm'
    ports:
      - 7070:8080
    networks:
      - dakar-network

networks:
  dakar-network:
    driver: bridge
volumes:
  post:
    driver: local
    driver_opts:
      type: none
      device: /home/dreaser/homeless/postgres/var/lib/postgresql/data
      o: bind
